volumes:
  postgres_db:

services:
  app:
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JAVA_OPTS: ${JAVA_OPTS}

  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}